import React from 'react'

export const LoansProfileData = [{
    clientName: 'Temidayo Adebayo',
    caseId: 'AAZU9068VG',
    phoneNumber: '09055555558',
    clientEmail: 'temidayo.bayo@gmail.com',
    loanOfficer: 'John Doe',
    loanType: 'Personal Loan',
    loanStatus: 'Active',
    firstName: 'Temidayo',
    middleName: 'Janet',
    lastName: 'Adebayo',
    sex: 'Female',
    dateOfBirth: '04/12/1975',
    maritalStatus: 'Married',
    emailAddress: 'temidayo.b@gmail.com',
    personalNumber: '09055555558',
    nin: '237569103853',
    address: 'Olowoporoku Close, Gbagada Estate, Lagos',
    tenancy: '02/01/2015',
    placeOfWork: 'Nigerian Aviation',
    jobTitle: 'Air Hostess',
    workEmail: 'atemiday@ngair.org.rg',
    staffNumber: 'NGA7890',
    startDate: '04/05/2013',
    endDate: 'N/A',
    companyAddress: 'SANCO Complex, MMA2 Ikeja, Lagos',
    fullName: 'Solomon Adebayo',
    employmentStatus: 'Employed',
    guarantorEmail: 'bayo.s@gmail.com',
    guarantorNumber: '07055555559',
    guarantorDOB: '12/04/2010',
    guarantorNIN:'224567896808',
    guarantorWork: 'Greene Logistics',
    guarantorWorkAddress: '12, Herbert Marculay way, Ikoyi, Lagos',
    id: 1
}]

  
